name: unlock
description: "Rede social gamificada com conexões autênticas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Services
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.8
  firebase_analytics: ^11.4.6          # ✅ Analytics
  firebase_crashlytics: ^4.3.6         # ✅ Crash reporting
  firebase_storage: ^12.4.6
  firebase_app_check: ^0.3.2+6
  firebase_performance: ^0.10.1        # ✅ Performance monitoring

  # Analytics Providers (Opcionais)
  # amplitude_flutter: ^3.14.0         # ✅ Descomente para usar Amplitude
  # mixpanel_flutter: ^2.2.0           # ✅ Descomente para usar Mixpanel

  # Authentication
  google_sign_in: ^6.2.1

  # Notifications & Background
  flutter_local_notifications: ^19.2.1
  workmanager: ^0.6.0
  permission_handler: ^11.0.1

  # State Management
  flutter_riverpod: ^2.6.1  
  riverpod_annotation: ^2.3.3

  # Storage & Cache
  shared_preferences: ^2.5.3

  # Navigation
  go_router: ^15.1.3

  # UI & Design
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.2
  equatable: ^2.0.5
  timeago: ^3.7.1

  # Logging & Analytics
  logger: ^2.5.0                       # ✅ Logging

  # External Actions
  share_plus: ^11.0.0        
  url_launcher: ^6.2.1 

  # Validation & Security
  validators: ^3.0.0
  crypto: ^3.0.6

  # App Icons
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

  # Analysis & Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/animations/
    - assets/sounds/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # Android 5.0
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#6366F1"
    theme_color: "#6366F1"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48