name: unlock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: # núcleo do Firebase
  firebase_auth: # autenticação
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.8
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6
  firebase_storage: ^12.4.6
  firebase_app_check: ^0.3.2+6  # ✅ Versão corrigida
  google_sign_in: # login com Google
  flutter_local_notifications: ^19.2.1
  flutter_animate: ^4.5.2

  workmanager: ^0.6.0
  permission_handler: ^11.0.1

# State Management
  flutter_riverpod: ^2.6.1  
  riverpod_annotation: ^2.3.3

# Storage
  shared_preferences: ^2.5.3

# Navigation
  go_router: ^15.1.3

# UI & Animation
  google_fonts: ^6.1.0
  lottie: ^3.3.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0

# Utilities
  intl: ^0.20.2
  uuid: ^4.2.2
  equatable: ^2.0.5
  logger: ^2.0.1
  timeago: ^3.7.1

# External Actions
  share_plus: ^11.0.0        
  url_launcher: ^6.2.1 

# Validation
  validators: ^3.0.0
  crypto: ^3.0.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

# Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
